name: Deploy sphinx documentation

on: [push, pull_request]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: pip install sphinx myst_parser furo sphinx-book-theme sphinxcontrib-googleanalytics sphinx_sitemap sphinx-togglebutton
      - name: Sphinx build
        run: sphinx-build theoretical_universe/ doc/
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          deploy_key: ${{ secrets.deploy_key2 }}
          publish_dir: doc/
          force_orphan: true
